systemLog:
  destination: file
  path: /data/workspace/MongoDB_Migration_Test/logs/aws_primary.log
  logAppend: true
storage:
  dbPath: /data/workspace/MongoDB_Migration_Test/data/aws_primary
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.3
net:
  port: 27017
  bindIp: 0.0.0.0
replication:
  replSetName: rs_migration
  oplogSizeMB: 256
processManagement:
  fork: true
  pidFilePath: /data/workspace/MongoDB_Migration_Test/data/aws_primary/mongod.pid
