systemLog:
  destination: file
  path: /data/workspace/MongoDB_Migration_Test/logs/tcloud_secondary.log
  logAppend: true
storage:
  dbPath: /data/workspace/MongoDB_Migration_Test/data/tcloud_secondary
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.3
net:
  port: 27018
  bindIp: 0.0.0.0
replication:
  replSetName: rs_migration
  oplogSizeMB: 256
processManagement:
  fork: true
  pidFilePath: /data/workspace/MongoDB_Migration_Test/data/tcloud_secondary/mongod.pid
